### ISSUE TITLE
Keep getting an issue running the first code

### ISSUE THREAD

**Issue by hanseulallyoh** [Janga-Lab/CASowary#1]
Hi, 

I've been trying to test the gRNA efficiency with your tool. However, I keep getting an error while trying to run the first code.

When I run this:
python CASowary_Preprocess.py Gene.csv -o Input_Guides.fasta

`Traceback (most recent call last):
  File "/Users/hanseulallyoh/gRNA_test/CASowary_Preprocess.py", line 90, in <module>
    Determine_Guides(input_List)
  File "/Users/hanseulallyoh/gRNA_test/CASowary_Preprocess.py", line 45, in Determine_Guides
    if (trx_Gene in gene_Name):
UnboundLocalError: local variable 'trx_Gene' referenced before assignment`

I keep getting this error message. Do you have any suggestion what I can do?

**Comment by xmkrohannon** [comment]
Hello,

The problem is arising because the file that CASowary searches: Gene Information.txt is not properly being stored on GitHub. GitHub appears to have changed their policy on storing large files. I will look into getting a resolution for this issue. Thank you for bringing this to my attention.

In the interim, I will provide a link to the file tomorrow. I'm traveling today and don't have access to the file at this time.

**Comment by xmkrohannon** [comment]
Hello,

GitHub no longer allows files larger than 50MB, resulting in the delisting of Gene_Information.txt and hg38_transcriptome_0221.fasta. I've made these files available at the following link. You should be able to directly download them from here.

https://indiana-my.sharepoint.com/personal/amkrug_iu_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Famkrug%5Fiu%5Fedu%2FDocuments%2FCASowary%2FPublished%20Version&view=0

I've also updated the ReadMe to include instructions to download from this link as well. This should resolve your problem. Let me know if you have any additional problems.

**Comment by hanseulallyoh** [comment]
Hi, thanks for working on this fast. 

However, I came across another problem of not being able to access the link. It seems like it is only available with the @iu.edu account login which I don't have. 

AADSTS90072: User account '**(my microsoft account)**' from identity provider 'live.com' does not exist in tenant 'Indiana University' and cannot access the application '00000003-0000-0ff1-ce00-000000000000'(Office 365 SharePoint Online) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account

Would it be possible for you to give another link open to public?

**Comment by xmkrohannon** [comment]
Can you try the following link? It should be available to the public now. If you still don't have access, I'll look into another platform for storage.

https://indiana-my.sharepoint.com/:f:/g/personal/amkrug_iu_edu/Et2HtXXEQLBDpFzbM_cbDc4B2yiQwJEK9YiJeEOOJYOPIA?e=PbUGCt

**Comment by hanseulallyoh** [comment]
This link worked. Thank you. 

However, while trying run this code, it starts showing me another error:

`tophat --read-mismatches 3 --read-edit-dist 3 -o Gene_Guides ./BT_hg38_transcriptome_0221/BT_hg38_transcriptome_0221 Input_Guides.fasta`

[2023-07-31 15:04:59] Checking for Bowtie index files (genome)..
Error: Could not find Bowtie 2 index files (./BT_hg38_transcriptome_0221/BT_hg38_transcriptome_0221.*.bt2l)

Do you have any idea how I can fix this?

**Comment by xmkrohannon** [comment]
Hello.

Tophat is an aligner that requires a Bowtie index file to quickly and efficiently perform its alignment. Before running tophat you should use the Bowtie application to build an index for the reference genome. In the above example the index files are in the BT_hg38_transcriptome_0221 folder with the file prefix BT_hg38_transcriptome_0221. Feel free to replace these names with whatever name works best for you. 

Tophat:
https://ccb.jhu.edu/software/tophat/index.shtml

Bowtie:
https://bowtie-bio.sourceforge.net/manual.shtml

**Comment by hanseulallyoh** [comment]
Everything worked out, thank you so much for your quick and helpful response !

**Comment by hanseulallyoh** [comment]
Hello, just a quick question:
Does CASowary only work on Hek293 cells and Hela cells as it is trained with the occupancy profile of Hek293 and Hela cells? Or if I find the occupancy profile of other cell types (e.g. myoblast), then can I also use this tool to find the optimal gRNA?

**Comment by xmkrohannon** [comment]
Great. Yes, you should be able to generate predictions for any cells that have corresponding occupancy profile data. You will just need to change the peak file, the -p option.
